/*
 * Books API
 *
 * This web service offers information on books
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/jdn0215/jdn0215-UNA-50118-Tarea3-115850529/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
		log.Fatal(http.ListenAndServe(":"+os.Getenv("PORT"), router))
}
